# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded PestiferUtil 1.0 [list source [file join $dir util.tcl]]
package ifneeded PestiferCRot 1.0 [list source [file join $dir crot.tcl]]
package ifneeded PestiferDeclash 1.0 [list source [file join $dir declash.tcl]]
package ifneeded PestiferAUTools 1.0 [list source [file join $dir autools.tcl]]
package ifneeded PestiferAxes 1.0 [list source [file join $dir axes.tcl]]
package ifneeded PestiferGetLinks 1.0 [list source [file join $dir getlinks.tcl]]
package ifneeded PestiferMultimer 1.0 [list source [file join $dir multimer.tcl]]
package ifneeded PestiferPierce 1.0 [list source [file join $dir checkpierce.tcl]]
package ifneeded PestiferEnviron 1.0 [list source [file join $dir environ.tcl]]
