version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - sphinx-apidoc -f -M -e --implicit-namespaces --tocfile API -o docs/source/api pestifer/
      - cd docs/source && yclept  make-doc ../../pestifer/resources/ycleptic/base.yaml --root config_ref --footer-style raw-html
    post_install:
      - pip install pdb2pqr --no-deps

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
