# pestifer; default configuration file
#
# you probably to not want to edit this file directly
#
# Cameron F. Abrams, cfa22@drexel.edu
#
StdCharmmTopo:
  - top_all36_prot.rtf
  - top_all35_ethers.rtf
  - top_all36_cgenff.rtf
  - top_all36_lipid.rtf
  - top_all36_na.rtf
  - stream/carb/toppar_all36_carb_glycopeptide.str

StdCharmmParam:
  - par_all36_prot.prm
  - par_all36_carb.prm
  - par_all36_lipid.prm
  - par_all36_na.prm
  - par_all36_cgenff.prm
  - stream/carb/toppar_all36_carb_glycopeptide.str

LocalCharmmTopo:
  - top_all36_carb.rtf
  - toppar_water_ions.str

LocalCharmmParam:
  - toppar_water_ions.str

PDBAliases:
  - residue HIS HSD
  - atom ILE CD1 CD
  - residue NAG BGNA
  - atom BGNA C7 C
  - atom BGNA O7 O
  - atom BGNA C8 CT
  - atom BGNA N2 N
  - residue SIA ANE5
  - atom ANE5 C10 C
  - atom ANE5 C11 CT
  - atom ANE5 N5 N
  - atom ANE5 O1A O11
  - atom ANE5 O1B O12
  - atom ANE5 O10 O
  - atom VCG C01 C1
  - atom VCG C01 C1
  - atom VCG C02 C2
  - atom VCG C03 C3
  - atom VCG C04 C4
  - atom VCG C05 C5
  - atom VCG C06 C6
  - atom VCG C07 C7
  - atom VCG C08 C8
  - atom VCG C09 C9
  - residue EIC LIN
  - residue MAN AMAN
  - residue BMA BMAN

PDB_to_CHARMM_Resnames:
  HIS: HSE
  ZN: ZN2
  HOH: TIP3
  CL: CLA
  NAG: BGNA
  MAN: AMAN
  BMA: BMAN
  FUC: AFUC
  GAL: BGAL
  SIA: ANE5AC
  ANE5: ANE5AC
  EIC: LIN
  VCG: VCG

PDB_to_CHARMM_Atomnames:
  CL: CLA
  O: OH2

PDB_1char_to_3char_Resnames:
  A: ALA
  R: ARG
  N: ASN
  D: ASP
  C: CYS
  Q: GLN
  E: GLU
  G: GLY
  H: HSE
  I: ILE
  L: LEU
  K: LYS
  M: MET
  F: PHE
  P: PRO
  S: SER
  T: THR
  W: TRP
  Y: TYR
  V: VAL

PDB_Ions:
  - LIT
  - SOD
  - MG
  - POT
  - CAL
  - RUB
  - CES
  - BAR
  - ZN
  - CAD
  - CL
  - SO4

PDB_Glycans:
  - BMA
  - FUC
  - GAL
  - MAN
  - NAG
  - SIA
  - ANE5

PDB_Ligands:
  - EIC
  - VCG

Segname_chars:
  PROTEIN: ''
  ION: I
  WATER: W
  GLYCAN: G
  LIGAND: L
  OTHER: O

User_defaults:
  vmd_startup: pestifer-vmd.tcl
  vmd_scriptname: vmd.tcl
  psfgen_scriptname: psfgen.tcl
  vmd: /usr/local/bin/vmd
  charmm_path: $(HOME)/charmm
  namd2: /usr/local/bin/namd2
  charmrun: /usr/local/bin/charmrun
  namd2_configbasename: namd2in
  Sacrificial_residue:
    name: GLY
    min_loop_length: 3
  Include_terminal_loops: False
  Fix_engineered_mutations: True
  Fix_conflicts: True

Namd_defaults:
  generic:
    paraTypeCharm: on
    exclude: scaled1-4
    1-4scaling: 1.9
    cutoff: 10.0
    switching: on
    switchdist: 9.0
    pairlistdist: 11.5
  vacuum:
    nonbondedFreq: 1
    fullElectFrequency: 2
    stepspercycle: 4
    dielectric: 80
    timestep: 1.0
    rigidbonds: none
  solvated:
    timestep: 2.0
    rigidbonds: all
    nonbondedFreq: 1
    fullElectFrequency: 2
    stepspercycle: 10
    PME: on 
    pmegridspacing: 1.0
  thermostat:
    langevin: on 
    langevinDamping: 5
    langevinTemp: $temperature
    langevinHydrogen: no 
  barostat:
    langevinpiston: on 
    langevinpistontarger: $pressure
    langevinpistonperiod: 200
    langevinpistondcay: 100
    langevinpistontemp: $temperature
    usegrouppressure: yes
    useflexiblecell: no
  mustset:
    - structure
    - coordinates
    - parameters
    - seed
    - outputName
    - outputEnergies
    - dcdfreq
    - restartfreq
    - temperature