Title: SARS-CoV-2 Spike
SourcePDB: 7df3
BiologicalAssembly: 1
Temperature: 310
BuildSteps:
  - solvate: False
    mods:
      - glycans.yaml
    smdclose: True
    relax_steps: 
      - 10000
  - solvate: False
    mods:
      - cleavage.yaml
    relax_steps: 
      - 10000
  - solvate: True
    relax_steps:
      - 100
      - 200
      - 400
      - 800
      - 20000
OutputName: my_7df3
NAMD2: /home/cfa/namd/NAMD_2.14_Source/Linux-x86_64-g++/namd2
CHARMRUN: /home/cfa/namd/NAMD_2.14_Source/Linux-x86_64-g++/charmrun
VMD: /usr/local/bin/vmd
CHARMMDIR: /home/cfa/charmm
