title: Example Build 
steps:
  - name: generate
    source:  # will download 7df3.pdb if not present; will look for 7df3.psf but not find it!
      pdb: 7df3
      biological_assembly: 1
      chains: all
    tasks:
      - build:  # the source directive necessarily yields no psf, so a build must be the first task
      - smdclose:
      - relax:
          nsteps: 10000
          temperature: 310
  - name: solvate
    source: 
       pdb: generate
    tasks:
      - solvate:
      - relax_series:
          temperature: 310
          nsteps:
            - 100
            - 200
            - 400
            - 800
            - 20000
NAMD2: $(HOME)/namd/NAMD_2.14_Source/Linux-x86_64-g++/namd2
CHARMRUN: $(HOME)/namd/NAMD_2.14_Source/Linux-x86_64-g++/charmrun
VMD: /usr/local/bin/vmd
CHARMMDIR: $(HOME)/charmm
