title: Example Build 
steps:
  - name: generate
    source:
      pdb: 7df3
      biological_assembly: 1
      chains: all
    tasks:
      - build:
          mods:
            - glycans.yaml
      - smdclose:
      - relax:
          nsteps: 10000
          temperature: 310
  - name: cleave
    source: generate
    tasks:
      - build:
          mods:
            - cleavage.yaml
      - relax:
          nsteps: 10000
          temperature: 310
  - name: solvate
    source: cleave
    tasks:
      - solvate:
      - relax_series:
          temperature: 310
          nsteps:
            - 100
            - 200
            - 400
            - 800
            - 20000
NAMD2: $(HOME)/namd/NAMD_2.14_Source/Linux-x86_64-g++/namd2
CHARMRUN: $(HOME)/namd/NAMD_2.14_Source/Linux-x86_64-g++/charmrun
VMD: /usr/local/bin/vmd
CHARMMDIR: $(HOME)/charmm
