# Pestifer 1.0.1
# (c) 2023 Cameron F. Abrams, 2023
#
# Format description for user configuration file
# use "required: True" for scalar values that have no defaults but must be specified
# use "required: False" for any values that should not be assigned defaults
#
directives:
  - name: title
    type: str
    text: Meaningful title (optional)
    default: Pestifer
  - name: paths
    type: dict
    text: Allows user to specify various paths
    directives:
      - name: namd2
        type: str
        text: Path for namd2 executable
        default: /usr/local/bin/namd2
      - name: charmrun
        type: str
        text: Path for charmrun executable
        default: /usr/local/bin/charmrun
      - name: vmd
        type: str
        text: Path for vmd executable
        default: /usr/local/bin/vmd
      - name: charmmff
        type: str
        text: Path for standard charmm force-field distribution; note that pestifer comes with the July 2022 distribution included and this is used by default
        required: False
  - name: tasks
    type: list
    text: Specifies the tasks to be performed; each is a dictionary with a heading which is a reserved task name
    directives:
      - name: psfgen
        text: Parameters controlling initial psfgen run
        type: dict
        directives:
          - name: source
            text: Specifies the source of the initial coordinate file
            type: dict
            directives:
              - name: id 
                text: The 4-character PDB ID of the source
                type: str
                required: True
              - name: biological_assembly 
                text: integer index of the biological assembly to construct; default is 0, signifying that the asymmetric unit is to be used
                type: int
                default: 0
              - name: file_format
                text: either PDB or mmCIF; some entries do not have a PDB-format file.  The main advantage of PDB is that it uses the author-designations for chains by default.  mmCIF is the new "default" format of the PDB.
                type: str
                choices: [PDB, mmCIF]
                default: PDB
              - name: exclude
                text: Specifies any residues or atoms to exclude from the system
                type: dict
                directives:
                  - name: chains
                    text: Specify list of chain IDs to ignore; in PDB-format input, these are typically author-generated, while in mmCIF they are not.  You must use chain IDs that reference your chosen coordinate file input format.
                    type: list
                    required: False
                  - name: resnames
                    text: Specify list of resnames to ignore; good for exluding waters or ions.  Resnames must reference your chosen coordinate input file.
                    type: list
                    required: False
              - name: sequence
                text: Parameters controlling sequence modifications based on specifications in the PDB file
                type: dict
                directives:
                  - name: include_terminal_loops
                    text: Specifies whether or not N- and C- terminal loops (if unresolved) are built in
                    type: bool
                    default: False
                  - name: fix_engineered_mutations
                    text: Specifies whether or not sequence differences w.r.t. a sequence database and which are labeled as "engineered mutation"s are reverted to their database values
                    type: bool
                    default: True 
                  - name: fix_conflicts 
                    text: Specifies whether or not sequence differences w.r.t. a sequence database and which are labeled as "conflicts"s are reverted to their database values
                    type: bool
                    default: True          
          - name: loops
            text: Parameters controlling model-built loops during psfgen
            type: dict
            directives:
              - name: sac_res_name 
                text: 3-letter code of residue appended to any sufficiently long model-built 
                type: str
                default: GLY
              - name: min_loop_length
                text: Minimum length of model-built loop that triggers the ligation algorithm
                type: int
                default: 4
              - name: declash
                text: Specifies how model-built residues are moved to avoid steric clashes
                type: dict
                directives:
                  - name: maxcycles
                    text: Maximum number of Metropolis cycles
                    type: int
                    default: 20
          - name: mods
            text: Specifies modifications to the sequence or structure in the PDB file
            type: dict
            directives:
              - name: mutations
                text: Single-residue mutations
                type: list
                required: False
          - name: minimize 
            text: Specifies the energy minimization to be performed on the output of psfgen
            type: dict
            directives:
              - name: nminsteps
                text: Number of iterations for the energy minimization
                type: int
                default: 1000
          - name: cleanup
            text: Specifies whether or not to delete temporary files generated during psfgen execution
            type: bool
            default: True
      - name: ligate
        text: Specifies how C-termini of model-built loops are connected back into their protein
        type: dict
        directives:
          - name: steer
            text: Specifies parameters for steered MD to bring C-termini close to their connection points
            type: dict
            directives:
              - name: force_constant
                text: force constant (kcal/mol/Angstrom^2)
                type: float
                default: 20
              - name: target_distant
                text: distance (Angstrom) between carbonyl carbon of loop C-terminus and amide nitrogen of connecting residue that steered MD drives to
                type: float
                default: 2
              - name: nsteps
                text: number of MD time steps for steeering
                type: int
                default: 1000
              - name: dcdfreq
                text: number of time steps between configuration output to DCD file
                type: int
                default: 100
          - name: connect
            text: Specifies parameters of the psfgen run that patches in the new backbone bonds
            type: dict
            directives:
              - name: cleanup
                text: Specifies whether or not to clean up temporary files
                type: bool
                default: True 
          - name: minimize
            text: Specifies the energy minimization to be performed on the output of psfgen
            type: dict
            directives:
              - name: nminsteps
                text: Number of iterations for the energy minimization
                type: int
                default: 1000
      - name: solvate
        text: Parameters controlling solvation and ionization
        type: dict
        directives:
          - name: minimize
            text: Specifies the energy minimization to be performed on the output of psfgen
            type: dict
            directives:
              - name: nminsteps
                text: Number of iterations for the energy minimization
                type: int
                default: 1000
      - name: relax
        text: Parameters controlling NVT or NPT equilibration
        type: dict
        directives:
          - name: ensemble
            text: Name of ensemble to run in
            type: str
            choices: [NVT, NPT]
            default: NVT
          - name: nminsteps
            text: Number of minimization steps
            type: int
            default: 0
          - name: nsteps
            text: Number of MD time steps
            type: int
            default: 1000
          - name: dcdfreq
            text: number of time steps between configuration output to DCD file
            type: int
            default: 100
          - name: xstfreq
            text: number of time steps between cell size output to DCD file
            type: int
            default: 100
          - name: temperature
            text: Temperature (K) for NVT or NPT
            type: float
            default: 300
          - name: pressure
            text: Pressure (bar) for NPT; note that NPT can only be peformed on a solvated system
            type: float
            default: 1
      - name: terminate
        text: Task that signals end of task list
        type: dict
        directives:
          - name: basename
            text: Desired basename for final psf/pdb files
            type: str
          - name: chainmapfile
            text: Desired name of the file describing all chain mapping
            type: str
            default: chainmaps.yaml
          - name: statefile
            text: Desired name of the file describing the current state
            type: str
            default: states.yaml
