Title: SARS-CoV-2 Delta S
Description: "Modifications to 7df3 PDB structure to generate the B.1.617.2 Delta variant; Step 1: Pre-cleavage modifications"
Author: Cameron F Abrams, cfa22@drexel.edu
Grafts:
  - source:
      pdb: 4byh
      chain_resids: C:1-10
      graft_resid: 1
    destinations:
      - chain_resid: K:1
        new_dest_resid: 0
      - chain_resid: I:1
        new_dest_resid: 0
      - chain_resid: E:1
        new_dest_resid: 0
      - chain_resid: D:1
        new_dest_resid: 0
      - chain_resid: S:1
        new_dest_resid: 0
      - chain_resid: Q:1
        new_dest_resid: 0
      - chain_resid: M:1
        new_dest_resid: 0
      - chain_resid: L:1
        new_dest_resid: 0
      - chain_resid: a:1
        new_dest_resid: 0
      - chain_resid: Y:1
        new_dest_resid: 0
      - chain_resid: U:1
        new_dest_resid: 0
      - chain_resid: T:1
        new_dest_resid: 0
      - chain_resid: A:1309
        new_dest_resid: 2509
      - chain_resid: A:1308
        new_dest_resid: 2608
      - chain_resid: A:1307
        new_dest_resid: 2707
      - chain_resid: A:1306
        new_dest_resid: 2806
      - chain_resid: A:1304
        new_dest_resid: 3004
      - chain_resid: A:1303
        new_dest_resid: 3103
      - chain_resid: B:1309
        new_dest_resid: 2509
      - chain_resid: B:1308
        new_dest_resid: 2608
      - chain_resid: B:1307
        new_dest_resid: 2707
      - chain_resid: B:1306
        new_dest_resid: 2806
      - chain_resid: B:1304
        new_dest_resid: 3004
      - chain_resid: B:1303
        new_dest_resid: 3103
      - chain_resid: C:1309
        new_dest_resid: 2509
      - chain_resid: C:1308
        new_dest_resid: 2608
      - chain_resid: C:1307
        new_dest_resid: 2707
      - chain_resid: C:1306
        new_dest_resid: 2806
      - chain_resid: C:1304
        new_dest_resid: 3004
      - chain_resid: C:1303
        new_dest_resid: 3103
  - source: 
      pdb: 4b7i
      chain_resids: C:1-8
      graft_resid: 1
    destinations:
      - chain_resid: A:1310
        new_dest_resid: 2410
      - chain_resid: B:1310
        new_dest_resid: 2410
      - chain_resid: C:1310
        new_dest_resid: 2410
      - chain_resid: J:1
        new_dest_resid: 0
      - chain_resid: A:1305
        new_dest_resid: 2905
      - chain_resid: F:1
        new_dest_resid: 0
      - chain_resid: G:1
        new_dest_resid: 0
      - chain_resid: A:1301
        new_dest_resid: 3301
      - chain_resid: R:1
        new_dest_resid: 0
      - chain_resid: B:1305
        new_dest_resid: 2905
      - chain_resid: N:1
        new_dest_resid: 0
      - chain_resid: O:1
        new_dest_resid: 0
      - chain_resid: B:1301
        new_dest_resid: 3301
      - chain_resid: Z:1
        new_dest_resid: 0
      - chain_resid: C:1305
        new_dest_resid: 2905
      - chain_resid: V:1
        new_dest_resid: 0
      - chain_resid: W:1
        new_dest_resid: 0
      - chain_resid: C:1301
        new_dest_resid: 3301
  - source: 
      pdb: 2wah
      chain_resids: C:1-9
      graft_resid: 1
    destinations:
      - chain_resid: H:1
        new_dest_resid: 0
      - chain_resid: A:1302
        new_dest_resid: 3202
      - chain_resid: P:1
        new_dest_resid: 0
      - chain_resid: B:1302
        new_dest_resid: 3202
      - chain_resid: X:1
        new_dest_resid: 0
      - chain_resid: C:1302
        new_dest_resid: 3202
Crotations:
  - type: GLYCAN
    segname: AG07
    resseqnum1: 3104
    atom1: O4
    resseqnum2: 3105
    atom2: C1
    degrees: -60
  - type: GLYCAN
    segname: BG07
    resseqnum1: 3104
    atom1: O4
    resseqnum2: 3105
    atom2: C1
    degrees: -60
  - type: GLYCAN
    segname: CG07
    resseqnum1: 3104
    atom1: O4
    resseqnum2: 3105
    atom2: C1
    degrees: -60