name: Release & Upload to PyPI & Archive at Zenodo

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: cameronabrams/workflows/.github/workflows/python-release.yml@main
    environment: pypi
    with:
      rtd_slug: pestifer
      run_tests: false
    secrets: inherit
